services:
  server1:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - internal
  server2:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - internal
  server3:
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - internal
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:8080
    networks:
      - loadBalancer
      - internal
    depends_on:
      - server1
      - server2
      - server3
  haproxy:
    image: haproxy:2.0-alpine
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    ports:
      - 8081:8080
    networks:
      - loadBalancer
      - internal
    depends_on:
      - server1
      - server2
      - server3

networks:
  loadBalancer:
    driver: bridge
  internal: {}