apiVersion: v1
kind: Pod
metadata:
  name: server1
  labels:
    app: nodejs
    env: arqsw2
spec:
  restartPolicy: Never
  containers:
  - image: arqsw2-server
    imagePullPolicy: IfNotPresent
    name: server
    resources: {}
    ports:
      - name: http
        containerPort: 3000
        protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: server2
  labels:
    app: nodejs
    env: arqsw2
spec:
  restartPolicy: Never
  containers:
  - image: arqsw2-server
    imagePullPolicy: IfNotPresent
    name: server
    resources: {}
    ports:
      - name: http
        containerPort: 3000
        protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: server3
  labels:
    app: nodejs
    env: arqsw2
spec:
  restartPolicy: Never
  containers:
    - image: arqsw2-server
      imagePullPolicy: IfNotPresent
      name: server
      resources: {}
      ports:
      - name: http
        containerPort: 3000
        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: nodejs
    env: arqsw2
    fruta: arqsw2
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30007
  selector:
    app: nodejs
    env: arqsw2