apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
  annotations:
    kubernetes.io/description: "Ejemplo de consumo de recursos con Kubernetes"
spec:
  containers:
  - name: memory-demo-ctr
    image: polinux/stress
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits: 
        memory: 200Mi
        cpu: 500m
    command: ["stress"]
    args: ["--vm", "1", "--vm-bytes", "180M", "--vm-hang", "1"]
